class EventsName:
    ProjectAdded="ProjectAdded"
    ProjectRestored = "ProjectRestored"
    ProjectStarted="ProjectStarted"
    ProjectStopped="ProjectStopped"
    ProjectPaused="ProjectPaused"
    ProjectResumed="ProjectResumed"
    ProjectCompleted="ProjectCompleted"
    ImageAdded="ImageAdded"
    PlotterAlarmSet="PlotterAlarmSet"
    CommandDone="CommandDone"
    PositionUpdated="PositionUpdated"
    ProjectOptimalized="ProjectOptimalized"